name: Terraform Apply
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  apply:
    runs-on: [self-hosted, 1ES.Pool=terraform-azure-modules]
    environment:
      name: tfstate
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
        with:
          submodules: "recursive"
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # 2.0.3
      - name: apply
        run: |
          az login --identity --username $MSI_ID > /dev/null
          export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
          export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
          export ARM_USE_MSI=true
          export TF_VAR_github_token=$GITHUB_TOKEN
          sh scripts/terragrunt-init.sh
          terraform apply -auto-approve -input=false -compact-warnings