name: Post Pull Request Cleanup
on:
  pull_request:
    types: [ 'closed' ]

jobs:
  cleanup:
    if: github.event.pull_request.merged != true
    runs-on: [self-hosted, 1ES.Pool=terraform-azure-modules]
    steps:
      - name: Delete tfplan file
        run: |
          az login --identity --username $MSI_ID > /dev/null
          echo "========> github.event.pull_request.merged is:"
          echo ${{github.event.pull_request.merged}}
          az storage blob delete --account-name tfmod1espoolstatestorage --container-name azure-verified-tfmod-pull-request-plans --name tfplan_${{ github.event.number }} --auth-mode login || echo "tfplan file cleanup error but we tolerate it."
