name: Pre Pull Request Check
on:
  pull_request:
    types: [ 'opened', 'synchronize', 'reopened']
    paths:
      - '.github/**'
      - '**.tf'
      - '**.tf.json'
      - '.github/workflows/**'

permissions:
  issues: write
  pull-requests: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  prepr-check:
    runs-on: [self-hosted, 1ES.Pool=terraform-azure-modules]
    environment:
      name: tfstate
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # 2.0.3
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@22b4647f1263865cda4473831640e71d349db2cd # 1.3.2
        with:
          terragrunt_version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: plan
        run: |
          az login --identity --username $MSI_ID > /dev/null
          export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
          export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
          export ARM_USE_MSI=true
          sh scripts/terragrunt-init.sh
          sh scripts/terragrunt-plan.sh
      - name: Upload plan file
        run: |
          az storage blob upload -f ./tfplan --account-name tfmod1espoolstatestorage --container-name azure-verified-tfmod-pull-request-plans --name tfplan_${{ github.event.number }} --tier Cool --no-progress --overwrite --auth-mode login
      - name: Save the PR number in an artifact
        env:
          PR_NUM: ${{ github.event.number }}
        run: echo $PR_NUM > pr_num.txt
      - name: Upload the PR number
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 #3.1.3
        with:
          name: pr_num
          path: ./pr_num.txt