---
name: Repository Data Generation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'

permissions:
  id-token: write
  contents: read

jobs:
  repository-data:
    name: Get Repository Data
    runs-on: ubuntu-latest
    environment: avm-updates

    steps:
      - name: Checkout Bootstrap Modules
        uses: actions/checkout@v4

      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1.11.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Get Repository Data
        run: |
          $repositories = @(./scripts/Invoke-RepoSyncGenerateMatrix.ps1)
          Write-Host (ConvertTo-Json $matrix -Depth 10)

          ./scripts/Invoke-RepoDataGeneration.ps1 -repositories $repositories

        shell: pwsh
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Upload Repo Data JSON
        uses: actions/upload-artifact@v4
        with:
          name: repositoryData.json
          path: repositoryData.json

      - name: Upload Repo Data CSV Files
        uses: actions/upload-artifact@v4
        with:
          name: CSV
          path: |
            *.csv

      - name: Upload Repo Logs Json
        if: always() && hashFiles('warning.log.json') != ''
        uses: actions/upload-artifact@v4
        with:
          name: warning.log.json
          path: warning.log.json

      - name: Repo Error
        if: always() && hashFiles('warning.log.json') != ''
        run: |
          $issueLogJson = Get-Content -Path "warning.log.json" -Raw
          $issueLog = ConvertFrom-Json $issueLogJson
          $issueLog | ForEach-Object {
            echo "::error title=$($_.repoId) has issues::$($_.message)"
          }
        shell: pwsh
